# Generated by Django 4.1.7 on 2025-01-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_eligible_for_testing',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='passed_testing',
        ),
    ]
