# Generated by Django 4.1.7 on 2025-01-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_profile_is_eligible_for_testing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recipient_email',
            field=models.EmailField(default='<EMAIL>', max_length=254),
        ),
    ]
