# Generated by Django 4.1.7 on 2025-01-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
