# Generated by Django 4.1.7 on 2025-01-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0020_delete_logging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Выполнено успешно'), ('comment', 'Внести комментарий'), ('not_done', 'Не сделано')], default='not_done', max_length=20)),
                ('points', models.IntegerField(default=300)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
