# Generated by Django 4.1.7 on 2025-01-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0022_remove_postcomment_article_remove_postcomment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.TextField(default='200'),
        ),
    ]
