# Generated by Django 4.1.7 on 2025-01-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0024_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(default='Almaty'),
        ),
    ]
