# Generated by Django 4.1.7 on 2025-01-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0025_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=200),
        ),
    ]
