# Generated by Django 4.1.7 on 2025-01-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0026_alter_profile_city_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(default='Almaty'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='add something here'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='forth',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='third',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images'),
        ),
    ]
