# Generated by Django 4.1.7 on 2025-01-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0027_alter_profile_city_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images'),
        ),
    ]
