# Generated by Django 4.1.7 on 2025-01-04 14:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0028_alter_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='UserProfile',
        ),
    ]
