# Generated by Django 4.1.7 on 2025-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0032_task_deadline_task_description_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recipient_email',
            field=models.EmailField(default='sarsendimas@gmail.com', max_length=254),
        ),
    ]
