# Generated by Django 4.1.7 on 2025-01-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0037_alter_task_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
    ]
