# Generated by Django 4.1.7 on 2025-01-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0039_remove_profile_first_remove_profile_forth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recipient_email',
        ),
    ]
